import {useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./portfolio.css';
import portrait from'./assets/figma/hero-portrait.png';import projectImage from'./assets/figma/project-placeholder.png';import articleImage from'./assets/figma/article-placeholder.png';import mail from'./assets/figma/contact-mail.svg';import whatsapp from'./assets/figma/contact-whatsapp.svg';import phone from'./assets/figma/contact-phone.svg';import location from'./assets/figma/contact-location.svg';
const nav=[['Home','home'],['About','about'],['My Projects','projects'],['My Services','services'],['My Stack','stack'],['Articles','articles']];const tech=['Vue.js','React','SQL Developer','SQLite','Svelte','Supabase','WordPress','Node.js','Next.js','Go','JavaScript','TypeScript','Flutter','MySQL','PostgreSQL','Redis','npm','Docker','HTML','CSS','Git','Linux','Figma','M-Pesa','Airtel Money','Pesapal','Flutterwave'];
function Socials(){return <div className="socials"><a href="https://linkedin.com">in</a><a href="https://github.com">gh</a><a href="https://x.com">𝕏</a><a href="mailto:hello@lawrenceobare.dev">dev</a></div>};function Heading({children,sub}){return <div className="heading"><h2>{children}</h2>{sub&&<p>{sub}</p>}</div>};function Carousel(){return <div className="carousel"><div className="dots">{[0,1,2,3,4,5].map(i=><i className={i?'':'on'} key={i}/>)}</div><div><button>←</button><button>→</button></div></div>}
function Navbar(){const[a,setA]=useState('home');const[o,setO]=useState(false);useEffect(()=>{let n=new IntersectionObserver(e=>e.forEach(x=>x.isIntersecting&&setA(x.target.id)),{rootMargin:'-35% 0px -55%'});document.querySelectorAll('main section').forEach(x=>n.observe(x));return()=>n.disconnect()},[]);return <header><nav><button className="menu" onClick={()=>setO(!o)}>Menu</button><div className={o?'links open':'links'}>{nav.map(([x,id])=><a className={a===id?'active':''} href={'#'+id} onClick={()=>setO(false)} key={id}>{x}</a>)}</div><a className="contactBtn" href="#contact">Contact me</a></nav></header>}
function Hero(){return <section className="hero" id="home"><div className="heroName">Lawrence <span>Obare</span></div><p className="greeting"><b>-</b> Hello there! I’m</p><div className="bigOrb"/><div className="smallOrb"/><img className="portrait" src={portrait} alt="Lawrence Obare"/><div className="heroText"><p>Backend-focused Full-Stack Software Engineer. Building practical software systems with Go, APIs, databases, payment integrations, and modern web technologies.</p><div><a className="outline" href="/Lawrence-Obare-CV.pdf">Download my CV</a><a className="black" href="#projects">View my work</a></div><div className="connect"><b>Lets connect</b><Socials/></div></div></section>}
function About(){return <section className="about" id="about"><div className="aboutCard"><h2>About Me</h2><div className="aboutImage"/><i/><p>I’m a backend-focused full-stack software engineer who builds practical, reliable products. I specialize in Go, backend architecture, APIs, databases, payment integrations, and the frontend systems that bring complete business workflows to life.</p></div></section>}
function Projects(){let x=['Payment Collection Platform','Business API Platform','Operations Dashboard'];return <section className="projects" id="projects"><div className="wide"><Heading>My <span>Projects</span></Heading><div className="cards">{x.map((t,i)=><article key={t}><img src={projectImage} alt=""/><h3>{t}</h3><p>{['Payment collection, transaction processing, reconciliation, and reporting.','Reliable backend services with authentication, business logic, and integrations.','Data-driven business workflows and operational visibility.'][i]}</p></article>)}</div><Carousel/></div></section>}
function Services(){let r=[['01.','Backend & API Development (Go)','I design backend architecture, REST APIs, authentication, business logic, data processing, and third-party integrations that are dependable in production.'],['02.','Full-Stack Web Development (JavaScript/TypeScript)','I connect frontend and backend systems into complete applications, from database to user interface and business workflow.'],['03.','Fintech & Payment Solutions','Payment collection, transaction processing, reconciliation, reporting, M-Pesa, Airtel Money, Pesapal, and Flutterwave integrations.'],['04.','UI/UX Design','Clear, responsive user interfaces and data-driven applications.']];let[e,setE]=useState(1);return <section className="services" id="services"><Heading><span>Services</span> I Provide</Heading><div>{r.map(([n,t,p],i)=><article className={e===i?'service expanded':'service'} key={n}><button onClick={()=>setE(e===i?null:i)}><b>{n}</b><span>{t}</span><i>↗</i></button>{e===i&&<p>{p}</p>}</article>)}</div></section>}
function Stack(){return <section className="stack" id="stack"><Heading>My <span>Stack</span></Heading><div>{tech.map(x=><span key={x}>{x}</span>)}</div></section>}
function Articles(){let x=['Designing APIs that are easy to use','Payment integrations: what to plan for','Why Go fits service-oriented products'];return <section className="articles" id="articles"><div className="articleWrap"><Heading sub="Notes on backend systems, product delivery, and practical engineering."><span>Articles</span> & <span>Posts</span></Heading><div className="articleCards">{x.map((t,i)=><article key={t}><img src={articleImage} alt=""/><small>{i+4} min read</small><h3>{t}</h3><p>Practical notes from building systems that are clear, dependable, and useful.</p><a href="#contact">Read more <b>→</b></a></article>)}</div><Carousel/></div></section>}
function Contact(){let x=[[mail,'Email','For project conversations and collaboration.','hello@lawrenceobare.dev','mailto:hello@lawrenceobare.dev'],[whatsapp,'WhatsApp','For a quick introduction or project question.','Start new chat','https://wa.me/'],[phone,'Phone','Available for focused project discussions.','+254 700 000 000','tel:+254700000000'],[location,'My Location','Working remotely with teams across regions.','Nairobi, Kenya','#contact']];return <section className="contact" id="contact"><div className="wide"><Heading sub="Have a product, integration, or operational challenge to solve? Let’s talk.">Contact <span>Me</span></Heading><div>{x.map(([im,t,p,l,h])=><article key={t}><img src={im} alt=""/><h3>{t}</h3><p>{p}</p><a href={h}>{l}</a></article>)}</div></div></section>}
function Footer(){return <footer><div><b>Quick links</b><nav>{nav.slice(1).map(([x,i])=><a href={'#'+i} key={i}>{x}</a>)}</nav><a className="email" href="mailto:hello@lawrenceobare.dev">Email Me Now</a><Socials/><hr/><small>© 2026 Lawrence Obare</small><aside><a>Privacy Policy</a><a>Terms of Service</a><a>Cookies Settings</a></aside></div></footer>};function App(){return <><Navbar/><main><Hero/><About/><Projects/><Services/><Stack/><Articles/><Contact/></main><Footer/></>};createRoot(document.getElementById('root')).render(<App/>);
